### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by Jentsch**
Hi ChristophKnabe,
while learning about akka with this code I found some minor opportunities to maybe improve the readability.

Kind regards

### CODE REVIEW

**Review by christophknabe — COMMENTED** [review]
Why do you think "closing over context" is bad?
Is it only for the reason of minimal redundancy (context.parent vs. parent) or are there more reasons behind it?
The other modification (foreach instead of explicit matching of Some) I understand well and agree with this simplification.

**Review by christophknabe — APPROVED** [review]
Looks good, especially method extension.

**Review by christophknabe — APPROVED** [review]

**Review by christophknabe — COMMENTED** [review]
Although the output of "Unscanned (not found | not completed) pages:" up to now was always empty, I think there is a chance, some pages do not completely get scanned.

**Comment by Jentsch** [comment]
May is misinterpreted the documentation of context but:

WARNING: [context is] Only valid within the Actor itself, so do not close over it and publish it to other threads!

See https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/Actor.scala#L460

**Review by christophknabe — COMMENTED** [review]
Thanks for the source code link to Actor. But I understand it so, that the problematic thing is to publish the context: ActorContext to other threads, not closing over it. So in my interpretation it would be bad to send a message to another Actor, which contains a reference to this ActorContext object.

**Review by christophknabe — APPROVED** [review]

**Review by christophknabe — APPROVED** [review]

**Review by christophknabe — APPROVED** [review]
This was an unused leftover from Heiko's project template.

**Comment by ChristophKnabe** [comment]
Many thanks for your feedback.

After inspection I merged your commits about **unused ActorSettings** and **worthToFollow** and pushed them to my repo at github.

**Comment by Jentsch** [comment]
But the code in e.g. `onComplete` could run within an other thread. There is, as far as I know, no guaranty with threads runs the code given to `onComple`.

**Pull request closed without merging**
